#!/bin/bash
/c/Users/SERREM/alx-system_engineering-devops/0x00-shell_basics
/c/Users/SERREM/alx-system_engineering-devops/0x00-shell_basics
/c/Users/SERREM/alx-system_engineering-devops/0x00-shell_basics
